services:
  telemetry_postgres:
    image: postgres:15
    restart: always
    ports:
      - '5444:5432' # External port 5444 → container's 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - telemetry_pgdata:/var/lib/postgresql/data
    networks:
      - telemetry_net

  telemetry_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3014:3014' # Expose telemetry service
    env_file:
      - .env
    depends_on:
      - telemetry_postgres
    networks:
      - telemetry_net
    command: >
      sh -c "
      npx prisma generate &&
      until npx prisma migrate dev --name init; do sleep 2; done &&
      pnpm dev
      "

volumes:
  telemetry_pgdata:

networks:
  telemetry_net:
